<?php

// =======================================================================================
// LOOM SUITE : LOOM SERVER (Copyright by wovencode.net)
//
//   --- DO NOT CHANGE ANYTHING BELOW THIS LINE (UNLESS YOU KNOW WHAT YOU ARE DOING) ---
// =======================================================================================

//====================================================================================
// CLIENT CONSTANTS
//====================================================================================

define('CONST_CLIENT_NAME_MAX_LENGTH',			32);					// (default 32) Maximum user name length for an account. Must be updated in database as well.
define('CONST_CLIENT_PASSWORD_MAX_LENGTH',		32);					// (default 32) Maximum password length for an account. Must be updated in database as well.
define('CONST_CLIENT_PASSWORD_GEN_LENGTH',		8);						// (default 8) length of passwords that are automatically generated by the server.

define('CONST_CLIENT_LIFETIME_CLIENT',			'180');					// (default 180) Seconds of inactivity before client session expires
define('CONST_CLIENT_LIFETIME_SESSION',			'1800');				// (default 1800) Seconds of inactivity before logged in user session expires
define('CONST_CLIENT_MAX_ACCOUNTS',				3);						// (default 3) Maximum accounts per device

define('CONST_CLIENT_MASK_IP',					0);						// (default 1) Mask the client IP address in the database? 1=Mask 0=Cleartext
define('CONST_CLIENT_MASK_AGENT',				0);						// (default 1) Mask the user device in the database? 1=Mask 0=Cleartext

//=====================================================================================EOF